database:
  address: 127.0.0.1:5432
  username: postgres
  password: postgres
  database: pets_backend

http_server:
  host: 127.0.0.1
  port: 8080
  shutdown_timeout: 5
  read_timeout: 10
  write_timeout: 10
  release: false

logger:
  output: stdout
  level: 5

smtp:
  user: example@gmail.com
  password: app_pass
  host: smtp.gmail.com
  port: 587
  otp_length: 4
  next_send_period_sec: 60
  exparation_time_min: 60

sso:
  token_lifespan_hours: 480
  secret_key: "some_key"