// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OtpCodesColumns holds the columns for the "otp_codes" table.
	OtpCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "code", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "next_send_time", Type: field.TypeTime},
		{Name: "exparation_time", Type: field.TypeTime},
	}
	// OtpCodesTable holds the schema information for the "otp_codes" table.
	OtpCodesTable = &schema.Table{
		Name:       "otp_codes",
		Columns:    OtpCodesColumns,
		PrimaryKey: []*schema.Column{OtpCodesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "unique_name", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OtpCodesTable,
		UsersTable,
	}
)

func init() {
}
