// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"pets-backend/internal/ent/otpcodes"
	"pets-backend/internal/ent/predicate"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OtpCodesQuery is the builder for querying OtpCodes entities.
type OtpCodesQuery struct {
	config
	ctx        *QueryContext
	order      []otpcodes.OrderOption
	inters     []Interceptor
	predicates []predicate.OtpCodes
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OtpCodesQuery builder.
func (ocq *OtpCodesQuery) Where(ps ...predicate.OtpCodes) *OtpCodesQuery {
	ocq.predicates = append(ocq.predicates, ps...)
	return ocq
}

// Limit the number of records to be returned by this query.
func (ocq *OtpCodesQuery) Limit(limit int) *OtpCodesQuery {
	ocq.ctx.Limit = &limit
	return ocq
}

// Offset to start from.
func (ocq *OtpCodesQuery) Offset(offset int) *OtpCodesQuery {
	ocq.ctx.Offset = &offset
	return ocq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ocq *OtpCodesQuery) Unique(unique bool) *OtpCodesQuery {
	ocq.ctx.Unique = &unique
	return ocq
}

// Order specifies how the records should be ordered.
func (ocq *OtpCodesQuery) Order(o ...otpcodes.OrderOption) *OtpCodesQuery {
	ocq.order = append(ocq.order, o...)
	return ocq
}

// First returns the first OtpCodes entity from the query.
// Returns a *NotFoundError when no OtpCodes was found.
func (ocq *OtpCodesQuery) First(ctx context.Context) (*OtpCodes, error) {
	nodes, err := ocq.Limit(1).All(setContextOp(ctx, ocq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{otpcodes.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ocq *OtpCodesQuery) FirstX(ctx context.Context) *OtpCodes {
	node, err := ocq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OtpCodes ID from the query.
// Returns a *NotFoundError when no OtpCodes ID was found.
func (ocq *OtpCodesQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ocq.Limit(1).IDs(setContextOp(ctx, ocq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{otpcodes.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ocq *OtpCodesQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ocq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OtpCodes entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OtpCodes entity is found.
// Returns a *NotFoundError when no OtpCodes entities are found.
func (ocq *OtpCodesQuery) Only(ctx context.Context) (*OtpCodes, error) {
	nodes, err := ocq.Limit(2).All(setContextOp(ctx, ocq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{otpcodes.Label}
	default:
		return nil, &NotSingularError{otpcodes.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ocq *OtpCodesQuery) OnlyX(ctx context.Context) *OtpCodes {
	node, err := ocq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OtpCodes ID in the query.
// Returns a *NotSingularError when more than one OtpCodes ID is found.
// Returns a *NotFoundError when no entities are found.
func (ocq *OtpCodesQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ocq.Limit(2).IDs(setContextOp(ctx, ocq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{otpcodes.Label}
	default:
		err = &NotSingularError{otpcodes.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ocq *OtpCodesQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ocq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OtpCodesSlice.
func (ocq *OtpCodesQuery) All(ctx context.Context) ([]*OtpCodes, error) {
	ctx = setContextOp(ctx, ocq.ctx, "All")
	if err := ocq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OtpCodes, *OtpCodesQuery]()
	return withInterceptors[[]*OtpCodes](ctx, ocq, qr, ocq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ocq *OtpCodesQuery) AllX(ctx context.Context) []*OtpCodes {
	nodes, err := ocq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OtpCodes IDs.
func (ocq *OtpCodesQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ocq.ctx.Unique == nil && ocq.path != nil {
		ocq.Unique(true)
	}
	ctx = setContextOp(ctx, ocq.ctx, "IDs")
	if err = ocq.Select(otpcodes.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ocq *OtpCodesQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ocq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ocq *OtpCodesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ocq.ctx, "Count")
	if err := ocq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ocq, querierCount[*OtpCodesQuery](), ocq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ocq *OtpCodesQuery) CountX(ctx context.Context) int {
	count, err := ocq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ocq *OtpCodesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ocq.ctx, "Exist")
	switch _, err := ocq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ocq *OtpCodesQuery) ExistX(ctx context.Context) bool {
	exist, err := ocq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OtpCodesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ocq *OtpCodesQuery) Clone() *OtpCodesQuery {
	if ocq == nil {
		return nil
	}
	return &OtpCodesQuery{
		config:     ocq.config,
		ctx:        ocq.ctx.Clone(),
		order:      append([]otpcodes.OrderOption{}, ocq.order...),
		inters:     append([]Interceptor{}, ocq.inters...),
		predicates: append([]predicate.OtpCodes{}, ocq.predicates...),
		// clone intermediate query.
		sql:  ocq.sql.Clone(),
		path: ocq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OtpCodes.Query().
//		GroupBy(otpcodes.FieldCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ocq *OtpCodesQuery) GroupBy(field string, fields ...string) *OtpCodesGroupBy {
	ocq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OtpCodesGroupBy{build: ocq}
	grbuild.flds = &ocq.ctx.Fields
	grbuild.label = otpcodes.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//	}
//
//	client.OtpCodes.Query().
//		Select(otpcodes.FieldCode).
//		Scan(ctx, &v)
func (ocq *OtpCodesQuery) Select(fields ...string) *OtpCodesSelect {
	ocq.ctx.Fields = append(ocq.ctx.Fields, fields...)
	sbuild := &OtpCodesSelect{OtpCodesQuery: ocq}
	sbuild.label = otpcodes.Label
	sbuild.flds, sbuild.scan = &ocq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OtpCodesSelect configured with the given aggregations.
func (ocq *OtpCodesQuery) Aggregate(fns ...AggregateFunc) *OtpCodesSelect {
	return ocq.Select().Aggregate(fns...)
}

func (ocq *OtpCodesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ocq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ocq); err != nil {
				return err
			}
		}
	}
	for _, f := range ocq.ctx.Fields {
		if !otpcodes.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ocq.path != nil {
		prev, err := ocq.path(ctx)
		if err != nil {
			return err
		}
		ocq.sql = prev
	}
	return nil
}

func (ocq *OtpCodesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OtpCodes, error) {
	var (
		nodes = []*OtpCodes{}
		_spec = ocq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OtpCodes).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OtpCodes{config: ocq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ocq.modifiers) > 0 {
		_spec.Modifiers = ocq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ocq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ocq *OtpCodesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ocq.querySpec()
	if len(ocq.modifiers) > 0 {
		_spec.Modifiers = ocq.modifiers
	}
	_spec.Node.Columns = ocq.ctx.Fields
	if len(ocq.ctx.Fields) > 0 {
		_spec.Unique = ocq.ctx.Unique != nil && *ocq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ocq.driver, _spec)
}

func (ocq *OtpCodesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(otpcodes.Table, otpcodes.Columns, sqlgraph.NewFieldSpec(otpcodes.FieldID, field.TypeUUID))
	_spec.From = ocq.sql
	if unique := ocq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ocq.path != nil {
		_spec.Unique = true
	}
	if fields := ocq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, otpcodes.FieldID)
		for i := range fields {
			if fields[i] != otpcodes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ocq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ocq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ocq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ocq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ocq *OtpCodesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ocq.driver.Dialect())
	t1 := builder.Table(otpcodes.Table)
	columns := ocq.ctx.Fields
	if len(columns) == 0 {
		columns = otpcodes.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ocq.sql != nil {
		selector = ocq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ocq.ctx.Unique != nil && *ocq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ocq.modifiers {
		m(selector)
	}
	for _, p := range ocq.predicates {
		p(selector)
	}
	for _, p := range ocq.order {
		p(selector)
	}
	if offset := ocq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ocq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (ocq *OtpCodesQuery) ForUpdate(opts ...sql.LockOption) *OtpCodesQuery {
	if ocq.driver.Dialect() == dialect.Postgres {
		ocq.Unique(false)
	}
	ocq.modifiers = append(ocq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return ocq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (ocq *OtpCodesQuery) ForShare(opts ...sql.LockOption) *OtpCodesQuery {
	if ocq.driver.Dialect() == dialect.Postgres {
		ocq.Unique(false)
	}
	ocq.modifiers = append(ocq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return ocq
}

// OtpCodesGroupBy is the group-by builder for OtpCodes entities.
type OtpCodesGroupBy struct {
	selector
	build *OtpCodesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ocgb *OtpCodesGroupBy) Aggregate(fns ...AggregateFunc) *OtpCodesGroupBy {
	ocgb.fns = append(ocgb.fns, fns...)
	return ocgb
}

// Scan applies the selector query and scans the result into the given value.
func (ocgb *OtpCodesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ocgb.build.ctx, "GroupBy")
	if err := ocgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OtpCodesQuery, *OtpCodesGroupBy](ctx, ocgb.build, ocgb, ocgb.build.inters, v)
}

func (ocgb *OtpCodesGroupBy) sqlScan(ctx context.Context, root *OtpCodesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ocgb.fns))
	for _, fn := range ocgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ocgb.flds)+len(ocgb.fns))
		for _, f := range *ocgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ocgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ocgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OtpCodesSelect is the builder for selecting fields of OtpCodes entities.
type OtpCodesSelect struct {
	*OtpCodesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ocs *OtpCodesSelect) Aggregate(fns ...AggregateFunc) *OtpCodesSelect {
	ocs.fns = append(ocs.fns, fns...)
	return ocs
}

// Scan applies the selector query and scans the result into the given value.
func (ocs *OtpCodesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ocs.ctx, "Select")
	if err := ocs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OtpCodesQuery, *OtpCodesSelect](ctx, ocs.OtpCodesQuery, ocs, ocs.inters, v)
}

func (ocs *OtpCodesSelect) sqlScan(ctx context.Context, root *OtpCodesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ocs.fns))
	for _, fn := range ocs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ocs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ocs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
