// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"pets-backend/internal/ent/otpcodes"
	"pets-backend/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OtpCodesDelete is the builder for deleting a OtpCodes entity.
type OtpCodesDelete struct {
	config
	hooks    []Hook
	mutation *OtpCodesMutation
}

// Where appends a list predicates to the OtpCodesDelete builder.
func (ocd *OtpCodesDelete) Where(ps ...predicate.OtpCodes) *OtpCodesDelete {
	ocd.mutation.Where(ps...)
	return ocd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ocd *OtpCodesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ocd.sqlExec, ocd.mutation, ocd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ocd *OtpCodesDelete) ExecX(ctx context.Context) int {
	n, err := ocd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ocd *OtpCodesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(otpcodes.Table, sqlgraph.NewFieldSpec(otpcodes.FieldID, field.TypeUUID))
	if ps := ocd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ocd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ocd.mutation.done = true
	return affected, err
}

// OtpCodesDeleteOne is the builder for deleting a single OtpCodes entity.
type OtpCodesDeleteOne struct {
	ocd *OtpCodesDelete
}

// Where appends a list predicates to the OtpCodesDelete builder.
func (ocdo *OtpCodesDeleteOne) Where(ps ...predicate.OtpCodes) *OtpCodesDeleteOne {
	ocdo.ocd.mutation.Where(ps...)
	return ocdo
}

// Exec executes the deletion query.
func (ocdo *OtpCodesDeleteOne) Exec(ctx context.Context) error {
	n, err := ocdo.ocd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{otpcodes.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ocdo *OtpCodesDeleteOne) ExecX(ctx context.Context) {
	if err := ocdo.Exec(ctx); err != nil {
		panic(err)
	}
}
