// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OtpCodes is the predicate function for otpcodes builders.
type OtpCodes func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
