// Code generated by ent, DO NOT EDIT.

package otpcodes

import (
	"pets-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldCode, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldEmail, v))
}

// NextSendTime applies equality check predicate on the "next_send_time" field. It's identical to NextSendTimeEQ.
func NextSendTime(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldNextSendTime, v))
}

// ExparationTime applies equality check predicate on the "exparation_time" field. It's identical to ExparationTimeEQ.
func ExparationTime(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldExparationTime, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldContainsFold(FieldCode, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldContainsFold(FieldEmail, v))
}

// NextSendTimeEQ applies the EQ predicate on the "next_send_time" field.
func NextSendTimeEQ(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldNextSendTime, v))
}

// NextSendTimeNEQ applies the NEQ predicate on the "next_send_time" field.
func NextSendTimeNEQ(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNEQ(FieldNextSendTime, v))
}

// NextSendTimeIn applies the In predicate on the "next_send_time" field.
func NextSendTimeIn(vs ...time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldIn(FieldNextSendTime, vs...))
}

// NextSendTimeNotIn applies the NotIn predicate on the "next_send_time" field.
func NextSendTimeNotIn(vs ...time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNotIn(FieldNextSendTime, vs...))
}

// NextSendTimeGT applies the GT predicate on the "next_send_time" field.
func NextSendTimeGT(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGT(FieldNextSendTime, v))
}

// NextSendTimeGTE applies the GTE predicate on the "next_send_time" field.
func NextSendTimeGTE(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGTE(FieldNextSendTime, v))
}

// NextSendTimeLT applies the LT predicate on the "next_send_time" field.
func NextSendTimeLT(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLT(FieldNextSendTime, v))
}

// NextSendTimeLTE applies the LTE predicate on the "next_send_time" field.
func NextSendTimeLTE(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLTE(FieldNextSendTime, v))
}

// ExparationTimeEQ applies the EQ predicate on the "exparation_time" field.
func ExparationTimeEQ(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldEQ(FieldExparationTime, v))
}

// ExparationTimeNEQ applies the NEQ predicate on the "exparation_time" field.
func ExparationTimeNEQ(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNEQ(FieldExparationTime, v))
}

// ExparationTimeIn applies the In predicate on the "exparation_time" field.
func ExparationTimeIn(vs ...time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldIn(FieldExparationTime, vs...))
}

// ExparationTimeNotIn applies the NotIn predicate on the "exparation_time" field.
func ExparationTimeNotIn(vs ...time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldNotIn(FieldExparationTime, vs...))
}

// ExparationTimeGT applies the GT predicate on the "exparation_time" field.
func ExparationTimeGT(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGT(FieldExparationTime, v))
}

// ExparationTimeGTE applies the GTE predicate on the "exparation_time" field.
func ExparationTimeGTE(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldGTE(FieldExparationTime, v))
}

// ExparationTimeLT applies the LT predicate on the "exparation_time" field.
func ExparationTimeLT(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLT(FieldExparationTime, v))
}

// ExparationTimeLTE applies the LTE predicate on the "exparation_time" field.
func ExparationTimeLTE(v time.Time) predicate.OtpCodes {
	return predicate.OtpCodes(sql.FieldLTE(FieldExparationTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OtpCodes) predicate.OtpCodes {
	return predicate.OtpCodes(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OtpCodes) predicate.OtpCodes {
	return predicate.OtpCodes(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OtpCodes) predicate.OtpCodes {
	return predicate.OtpCodes(sql.NotPredicates(p))
}
