name: CI

on:
    push:
        branches:
            - master
            - dev
    pull_request:

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.21'
                cache: false
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v4
              with:
                version: v1.54
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.21'
                cache: false
            - name: test
              run: |
                go test -coverprofile=coverage.out ./...
                go tool cover -func=coverage.out
                # COVERAGE=`go tool cover -func=coverage.out | grep total: | grep -Eo '[0-9]+\.[0-9]+'`
                # echo $COVERAGE      